name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

#[[d1_databases]]
#binding = "db"			#d1数据库绑定名默认不可修改
#database_name = "cloudmail_db"		#d1数据库名字
#database_id = "6932ae6d-bac9-4f88-9f79-b0b30df9a63c"		#d1数据库id

#[[kv_namespaces]]
#binding = "kv"			#kv绑定名默认不可修改
#id = "1dd0667d728742bc812e8b3ae66a3897"					#kv数据库id

#[[r2_buckets]]
#binding = "r2"			#r2对象存储绑定名默认不可修改
#bucket_name = "cloud-mail"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


#[vars]
#orm_log = false
#domain = [126330.xyz]				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
#admin = "admin@126330.xyz"				#管理员的邮箱	示例: admin@example.com
#jwt_secret = "b1bbbb8cdacd80d8062329195ce41a0c"			#jwt令牌的密钥,随便填一串字符串

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
